// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeOZdrWYbx3XD4pOHCzDaaz2NXe16KD6A',
    appId: '1:995888500438:web:f398db18880634d7e40377',
    messagingSenderId: '995888500438',
    projectId: 'luxeliving-60d75',
    authDomain: 'luxeliving-60d75.firebaseapp.com',
    storageBucket: 'luxeliving-60d75.appspot.com',
    measurementId: 'G-YMYQQMG4DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiEUZS22gmiTeIFgV5Zbe_hZgTXbrzdyA',
    appId: '1:995888500438:android:d42111523015c5b4e40377',
    messagingSenderId: '995888500438',
    projectId: 'luxeliving-60d75',
    storageBucket: 'luxeliving-60d75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBurACo9C8FAynPSN-w8LVimbrXdwxSRSE',
    appId: '1:995888500438:ios:e405dba6fb660672e40377',
    messagingSenderId: '995888500438',
    projectId: 'luxeliving-60d75',
    storageBucket: 'luxeliving-60d75.appspot.com',
    iosBundleId: 'com.example.luxeLiving',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBurACo9C8FAynPSN-w8LVimbrXdwxSRSE',
    appId: '1:995888500438:ios:e405dba6fb660672e40377',
    messagingSenderId: '995888500438',
    projectId: 'luxeliving-60d75',
    storageBucket: 'luxeliving-60d75.appspot.com',
    iosBundleId: 'com.example.luxeLiving',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeOZdrWYbx3XD4pOHCzDaaz2NXe16KD6A',
    appId: '1:995888500438:web:592d2f4c14d3ff99e40377',
    messagingSenderId: '995888500438',
    projectId: 'luxeliving-60d75',
    authDomain: 'luxeliving-60d75.firebaseapp.com',
    storageBucket: 'luxeliving-60d75.appspot.com',
    measurementId: 'G-DQY68GQ8RN',
  );
}
